name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Nuget Push
      run: cd bin\Release && dotnet nuget push 'C:\source\git\JasonDWilson\api-proxy-bridge\bin\Release\api-proxy-bridge.1.0.0.nupkg' --api-key oy2jomjcx42ks5fpyvvalt3b76pm5xeujkbkdzaismbmua --source https://api.nuget.org/ --skip-duplicate
